config/routes.rb
Flightscraper::Application.routes.draw do
  resources :base_routes do
    resources :scrapes
  end

  resources :scrapes
  resources :strikes

  root 'base_routes#index'

end

app/models/scrape.rb
class Scrape < ActiveRecord::Base

  serialize :base_route_ids, Array
  serialize :strike_ids, Array
  serialize :search_engine_ids, Array

  # validate
  validate :validate_date_string_format
  validate :validate_base_route_ids
  validate :validate_strike_ids
  validate :validate_search_engine_ids
  
  attr_accessor :base_routes
  attr_accessor :strikes
  attr_accessor :search_engines

  def date_string_format_valid?(date_string)
    # Valid: ((2013-03-01, 2013-03-5, 2013-04-5), (+1, +1, +1), (-1, -2, -1)) + 7 * 3, meaning (2013-03-01, 2013-03-5, 2013-04-5), (2013-03-02, 2013-03-6, 2013-04-6), (2013-02-28, 2013-03-4, 2013-04-4), repeated for the next 3 weeks
    # Maximum date variations 50 right now
    begin
      valid = true

      parsed_date_string = date_string.match /\A\s*\((.*)\)\s*\+\s*(\d*)\s*\*\s*(\d*)/
      
      # check dates
      begin
        parsed_date_string[1].match(/\((.*?)\)/)[1].split(',').map { |date| Date.parse date.strip }
      rescue Exception => e
        valid &&= false
      end
      
      # check following pairs
      parsed_date_string[1].scan(/\((.*?)\)/).drop(1).each do |pair|
        valid &&= false if pair.first.split(',').map { |el| el.strip.match(/\A[\+\-]\d\z/) }.any?(&:blank?)
      end

      # check accumulate number
      # (datepair + number of pairs) * multiplier
      valid &&= false if parsed_date_string[1].scan(/\((.*?)\)/).length * parsed_date_string.captures.last.to_i > 50

    rescue Exception => e
      return false
    end

    return valid
  end

  def validate_date_string_format
    errors.add(:date_string, "is malformatted") unless date_string_format_valid?(date_string)
  end

  def validate_base_route_ids
    errors.add(:base_route_ids, "is empty") if base_route_ids.empty?
    begin
      self.base_routes = BaseRoute.find base_route_ids
    rescue Exception => e
      errors.add(:base_route_ids, "some base routes could not be found")
    end
  end

  def validate_strike_ids
    begin
      self.strikes = Strike.find strike_ids
    rescue Exception => e
      errors.add(:strike_ids, "some strikes could not be found")
    end
  end

  def validate_search_engine_ids
    errors.add(:search_engine_ids, "is empty") if search_engine_ids.empty?
    begin
      self.search_engines = SearchEngine.find search_engine_ids
    rescue Exception => e
      errors.add(:search_engine_ids, "some search_engines could not be found")
    end
  end

  def get_all_date_pairs

    parsed_date_string = date_string.match /\A\s*\((.*)\)\s*\+\s*(\d*)\s*\*\s*(\d*)/

    # get the base date
    base_date_pair = parsed_date_string[1].match(/\((.*?)\)/)[1].split(',').map { |date| Date.parse date.strip }
    date_pairs = [base_date_pair]

    # add our modifiers to our set
    parsed_date_string[1].scan(/\((.*?)\)/).drop(1).each do |pair|
      date_pairs << base_date_pair.zip(pair.first.split(',').map(&:strip)).map { |(base_date, offset)| calculate_offset_from_base_date(base_date, offset) }
    end

    # get the multiplier in
    adder = parsed_date_string[-2].to_i
    multiplier = parsed_date_string[-1].to_i

    date_pairs.map! { |(start_date, end_date, strike_date)| (0..multiplier).to_a.map { |x| [start_date + (adder * x).days, end_date + (adder * x).days, strike_date + (adder * x).days ] } }

    date_pairs.flatten(1)

  end

  def calculate_offset_from_base_date(base_date, offset)
    case offset[0]
    when '+'
      return base_date + offset[1..-1].to_i
    when '-'
      return base_date - offset[1..-1].to_i
    else
      return base_date
    end
  end
  
end

app/controllers/scrapes_controller.rb
class ScrapesController < ApplicationController
  respond_to :html
  def new
    @scrape = Scrape.new

  end

  def create
    params[:scrape][:base_route_ids].pop(1) if params[:scrape][:base_route_ids].last == ''
    params[:scrape][:strike_ids].pop(1) if params[:scrape][:strike_ids].last == ''
    params[:scrape][:search_engine_ids].pop(1) if params[:scrape][:search_engine_ids].last == ''
    without_strike = true if params[:scrape][:strike_ids].delete '0'
    
    @scrape = Scrape.new params[:scrape].permit(:base_route_ids, :strike_ids, :search_engine_ids, :date_string)
    @scrape.base_route_ids = params[:scrape][:base_route_ids]
    @scrape.strike_ids = params[:scrape][:strike_ids]

    @scrape.search_engine_ids = params[:scrape][:search_engine_ids]
    
    if @scrape.valid?
      @priced_base_routes = []
      @priced_strike_routes = []
      # create all the priced thingys
      @scrape.get_all_date_pairs.each do |(start_date, end_date, strike_date)|
        @scrape.base_routes.each do |base_route|
          @scrape.search_engines.each do |search_engine|
            
            @scrape.strikes.each do |strike|
              @priced_strike_routes << PricedStrikeRoute.create(:search_engine => search_engine, :start_date => start_date, :end_date => end_date, :base_route => base_route, :strike => strike, :strike_date => strike_date).scrape_price
            end

            if without_strike
              @priced_base_routes << PricedBaseRoute.create(:search_engine => search_engine, :start_date => start_date, :end_date => end_date, :base_route => base_route).scrape_price
            end

          end
        end
      end

      render 'success'
    else
      render 'new'
    end
  end

  def index
    raise
    redirect_to :root
  end
end

app/helpers/scrapes_helper.rb
module ScrapesHelper

  def all_strikes
    [Strike.new(:id => 0, :origin => "Without Strike")] + Strike.all
  end

end

app/views/scrapes/success.html.erb
<% if !@priced_base_routes.blank? %>
<h1>Priced Base Routes</h1>
  <table>
    <thead>
      <tr>
        <th>Base-Pair</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>OTA</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% for route in @priced_base_routes %>
        <tr>
          <td><%= link_to route.base_route.to_s, base_route_path(route.base_route) %></td>
          <td><%= route.start_date %></td>
          <td><%= route.end_date %></td>
          <td><%= route.search_engine.name %></td>
          <td><%= route.price_string %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
<% end %>

<% if !@priced_strike_routes.blank? %>
<h1>Priced Strike Routes</h1>
  <table>
    <thead>
      <tr>
        <th>Base-Pair</th>
        <th>Strike</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Strike Date</th>
        <th>OTA</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% for route in @priced_strike_routes %>
        <tr>
          <td><%= link_to route.base_route.to_s, base_route_path(route.base_route) %></td>
          <td><%= link_to route.strike.to_s, strike_path(route.strike) %></td>
          <td><%= route.start_date %></td>
          <td><%= route.end_date %></td>
          <td><%= route.strike_date %></td>
          <td><%= route.search_engine.name %></td>
          <td><%= route.price_string %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  
<% end %>