config/routes.rb
Flightscraper::Application.routes.draw do
  resources :base_routes do
    resources :scrapes
  end

  resources :scrapes
  resources :strikes

  root 'base_routes#index'

end

app/models/base_route.rb
class BaseRoute < ActiveRecord::Base
  has_many :priced_base_routes
  has_many :priced_strike_routes

  def price_with_strike(search_engine, start_date, end_date, strike, strike_date) 
    price, currency = search_engine.scraper.scrape_round_trip_with_strike(self, strike, start_date, end_date, strike_date)
    self.priced_strike_routes.create :price => price, :currency => currency, :start_date => start_date, :end_date => end_date, :ota => ota, :strike => strike, :strike_date => strike_date
  end

  def price(search_engine, start_date, end_date)
    price, currency = search_engine.scraper.scrape_round_trip(self, start_date, end_date)
    self.priced_base_routes.create :price => price, :currency => currency, :start_date => start_date, :end_date => end_date, :ota => ota
  end

  def to_s
    "#{origin}-#{destination}"
  end

end

app/controllers/base_routes_controller.rb
class BaseRoutesController < ApplicationController
  respond_to :json, :html
  
  def index
    @base_routes = BaseRoute.all
  end

  def show
    @base_route = BaseRoute.find params[:id]
  end

  def new
    @base_route = BaseRoute.new
  end

  def create
    @base_route = BaseRoute.create params[:base_route].permit(:origin, :destination)
    respond_with @base_route
  end

end

app/helpers/base_routes_helper.rb
module BaseRoutesHelper
end

app/views/base_routes/index.html.erb
<h1>Base Routes</h1>

<% if !@base_routes.blank? %>
  <table>
    <thead>
      <tr>
        <th>Origin</th>
        <th>Destination</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% for base_route in @base_routes %>
        <tr>
          <td><%= base_route.origin %></td>
          <td><%= base_route.destination %></td>
          <td><%= link_to 'Show', base_route_path(base_route) %></td>
        </tr>
        
      <% end %>
    </tbody>
  
  </table>
<% else %>
  
<% end %>

<%= link_to "New Base Route", new_base_route_path  %>

app/views/base_routes/new.html.erb
<h1>New Base Route</h1>

<%= simple_form_for @base_route do |f| %>
  <%= f.input :origin %>
  <%= f.input :destination  %>
  <%= f.submit %>
<% end %>

app/views/base_routes/show.html.erb
<h1><%= @base_route.origin %> - <%= @base_route.destination %></h1>

<% if !@base_route.priced_base_routes.blank? %>
  <h3>Priced with this base route</h3>
  <table>
    <thead>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Price</th>
        <th>Currency</th>
        <th>OTA</th>
      </tr>
    </thead>
    <tbody>
    <% for priced_base_route in @base_route.priced_base_routes %>
      <tr>
        <th><%= priced_base_route.start_date %></th>
        <th><%= priced_base_route.end_date %></th>
        <th><%= priced_base_route.price %></th>
        <th><%= priced_base_route.currency %></th>
        <td><%= priced_base_route.search_engine.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  
<% end %>

<% if !@base_route.priced_strike_routes.blank? %>
  <h3>Priced and striked with this base route</h3>
  <table>
    <thead>
      <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Strike Date</th>
        <th>Strike</th>
        <th>Price</th>
        <th>Currency</th>
        <th>OTA</th>
      </tr>
    </thead>
    <tbody>
    <% for priced_strike_route in @base_route.priced_strike_routes %>
      <tr>
        <th><%= priced_strike_route.start_date %></th>
        <th><%= priced_strike_route.end_date %></th>
        <th><%= priced_strike_route.strike_date %></th>
        <th><%= priced_strike_route.strike %></th>
        <th><%= priced_strike_route.price %></th>
        <th><%= priced_strike_route.currency %></th>
        <td><%= priced_strike_route.search_engine.name %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  
<% end %>

<%= link_to "Schedule new Scrape" , new_base_route_scrape_path(@base_route) %>